return {
	"catppuccin/nvim",
	lazy = false,
	name = "catppuccin",
	main = "catppuccin",
	priority = 1000,
	config = function()
		require"catppuccin".setup({
			flavour = "mocha",
			background = {
				light = "latte",
				dark = "mocha",
			},
			transparent_background = false,
			show_end_of_buffer = true,
			term_colors = false,
			dim_inactive = {
				enabled = false,
				shade = "dark",
				percentage = 0.15,
			},
			no_italic = false,
			no_bold = false,
			no_underline = false,
			styles = {
				comments = { "italic" },
				conditionals = { "bold" },
				loops = {"bold" },
				functions = {},
				keywords = {"bold" },
				strings = {},
				variables = {"italic"},
				numbers = {},
				booleans = {},
				properties = {},
				types = {"italic"},
				operators = {},
			},
			color_overrides = {},
			custom_highlights = {},
			default_integrations = true,
			integrations = {
				cmp = true,
				gitsigns = true,
				nvimtree = true,
				treesitter = true,
				notify = true,
				alpha = true,
				coc_nvim = true,
				dashboard = true,
				harpoon = true,
				which_key = true,
				telescope = {
					enabled = true,
				},
				native_lsp = {
					enabled = true,
					virtual_text = {
						errors = { "italic" },
						hints = { "italic" },
						warnings = { "italic" },
						information = { "italic" },
						ok = { "italic" },
					},
					underlines = {
						errors = { "underline" },
						hints = { "underline" },
						warnings = { "underline" },
						information = { "underline" },
						ok = { "underline" },
					},
					inlay_hints = {
						background = true,
					},
				},
				mason = true,
				markdown = true,
				mini = {
					enabled = true,
					indentscope_color = "",
				},
			},
		})
	end,
}
